config/routes.rb
Rails.application.routes.draw do
  resources :test_posts
  resources :test_tags
  resources :test_articles

  # Test Resources
  resources :test_tags do
    collection do
      get :search
    end
  end
  resources :test_articles do
    collection do
      get :search
    end
  end
  resources :test_posts do
    collection do
      get :search
    end
  end

  # Core Resources
  resources :roles do
    collection do
      get :search
    end
  end
  resources :profiles do
    collection do
      get :search
    end
  end
  resources :groups do
    collection do
      get :search
    end
  end
  resources :users do
    collection do
      get :search
    end
  end
  resources :maps do
    collection do
      get :search
    end
  end

  # Defines the root path route ("/")
  root "homepage#index"

  get 'test/create' => 'homepage#create'
  get 'test/update' => 'homepage#update'
  get 'test/delete' => 'homepage#destroy'

  scope :sessions do
    devise_for :users, controllers: {
      confirmations: 'sessions/confirmations',
      onmiauth_callbacks: 'sessions/onmiauth_callbacks',
      passwords: 'sessions/passwords',
      registrations: 'sessions/registrations',
      sessions: 'sessions/sessions',
      unlocks: 'sessions/unlocks',
    }
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  scope :api do
    scope :v7 do
      resources :users
    end
  end

end

app/views/layouts/shared/_confirm.html.erb
<dialog id="turbo-confirm" class="rounded-lg shadow text-center">

  <div class="relative p-4 text-center bg-white rounded-lg shadow">
    <%= form_tag method: :delete do %>
      <%= icon('delete', 'text-gray-400 w-11 h-11 mb-3.5 mx-auto') %>
      <p class="mb-4 text-gray-500 dark:text-gray-300">Are you sure you want to delete this item?</p>
      <%= button_tag 'Confirmar', value: 'confirm', class: 'button-danger' %>
      <%= button_tag 'Cancelar', value: 'cancel', class: 'button-filter' %>
      <%= button_tag 'Cerrar', value: 'close', class: 'button-filter' %>
    <% end %>
  </div>

</dialog>

app/views/layouts/shared/_navigation.html.erb
<nav class="bg-white border-gray-200">
  <div class="flex flex-wrap justify-between items-center mx-auto max-w-full p-5">
    <%= link_to root_path, class: 'flex items-center' do %>
      <img src="https://i.vimeocdn.com/portrait/44439325_60x60" class="h-8 mr-3" alt="Flowbite Logo" />
      <span class="self-center text-2xl font-semibold whitespace-nowrap dark:text-white">AIM Manager</span>
    <% end %>
    <div class="hidden w-full md:block md:w-auto" id="navbar-default">
      <ul class="font-medium flex flex-col p-4 md:p-0 mt-4 border border-gray-100 rounded-lg bg-gray-50 md:flex-row md:space-x-8 md:mt-0 md:border-0 md:bg-white">
        <li><%= link_to 'Posts', test_posts_path, class: 'block py-2 pl-3 pr-4 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0' %></li>
        <li><%= link_to 'Articles', test_articles_path, class: 'block py-2 pl-3 pr-4 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0' %></li>
        <li><%= link_to 'Tags', test_tags_path, class: 'block py-2 pl-3 pr-4 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0' %></li>
        <li><%= link_to 'Users', users_path, class: 'block py-2 pl-3 pr-4 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0' %></li>
        <li><%= link_to 'Groups', groups_path, class: 'block py-2 pl-3 pr-4 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0' %></li>
        <li><%= link_to 'Profiles', profiles_path, class: 'block py-2 pl-3 pr-4 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0' %></li>
        <li><%= link_to 'Roles', roles_path, class: 'block py-2 pl-3 pr-4 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0' %></li>
        <li><%= link_to 'Maps', maps_path, class: 'block py-2 pl-3 pr-4 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0' %></li>
        <li><%= link_to 'Salir', destroy_user_session_path, data: { "turbo-method": :delete } , class: 'block py-2 pl-3 pr-4 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0' %></li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/shared/_notification.html.erb
<div class="notification-wrapper" >
    <div class="notification-container">
      <%= turbo_frame_tag "notification" do %>
        <% flash.delete(:timedout).each do |key, value| %>
          <% value = [] << value if value.kind_of? String %>
          <% value.each_with_index do |message, index| %>
            <div
                class="notification <%= notification_class(key.to_sym) %> hidden"
                id="toast-<%= key %>-<%= index %>"
                role="alert"
                data-controller="notification"
                data-notification-delay-value="100000"
                data-transition-enter-active="transition ease-out duration-1000"
                data-transition-enter-from="transform opacity-0 translate-x-6"
                data-transition-enter-to="transform opacity-100 translate-x-0"
                data-transition-leave-active="transition ease-in duration-1000"
                data-transition-leave-from="transform opacity-100 translate-x-0"
                data-transition-leave-to="transform opacity-0 translate-x-6"
            >
              <div class="notification-icon"><%= notification_icon(key) %></div>
              <div class="notification-message"><%= message %></div>
              <%= button_tag raw(icon('close', 'w-3 h-3')), type: 'button', class: "notification-close", data: { 'dismiss-target': "#toast-#{key}-#{index}", 'aria-label': "Close" } %>
            </div>
          <% end %>
        <% end %>
      <% end %>
    </div>
</div>

app/views/layouts/shared/_notification_row.html.erb
<%= turbo_frame_tag "notification" do %>
  <% flash.delete(:timedout).each do |key, value| %>
    <% value = [] << value if value.kind_of? String %>
    <% value.each_with_index do |message, index| %>
      <div
        class="notification <%= notification_class(key.to_sym) %> hidden"
        id="toast-<%= key %>-<%= index %>"
        role="alert"
        data-controller="notification"
        data-notification-delay-value="100000"
        data-transition-enter-active="transition ease-out duration-1000"
        data-transition-enter-from="transform opacity-0 translate-x-6"
        data-transition-enter-to="transform opacity-100 translate-x-0"
        data-transition-leave-active="transition ease-in duration-1000"
        data-transition-leave-from="transform opacity-100 translate-x-0"
        data-transition-leave-to="transform opacity-0 translate-x-6"
      >
      <div class="notification-icon"><%= notification_icon(key) %></div>
      <div class="notification-message"><%= message %></div>
        <%= button_tag raw(icon('close', 'w-3 h-3')), type: 'button', class: "notification-close", data: { 'dismiss-target': "#toast-#{key}-#{index}", 'aria-label': "Close" } %>
      </div>
    <% end %>
  <% end %>
<% end %>