config/routes.rb
Rails.application.routes.draw do
  resources :test_posts
  resources :test_tags
  resources :test_articles

  # Test Resources
  resources :test_tags do
    collection do
      get :search
    end
  end
  resources :test_articles do
    collection do
      get :search
    end
  end
  resources :test_posts do
    collection do
      get :search
    end
  end

  # Core Resources
  resources :roles do
    collection do
      get :search
    end
  end
  resources :profiles do
    collection do
      get :search
    end
  end
  resources :groups do
    collection do
      get :search
    end
  end
  resources :users do
    collection do
      get :search
    end
  end
  resources :maps do
    collection do
      get :search
    end
  end

  # Defines the root path route ("/")
  root "homepage#index"

  get 'test/create' => 'homepage#create'
  get 'test/update' => 'homepage#update'
  get 'test/delete' => 'homepage#destroy'

  scope :sessions do
    devise_for :users, controllers: {
      confirmations: 'sessions/confirmations',
      onmiauth_callbacks: 'sessions/onmiauth_callbacks',
      passwords: 'sessions/passwords',
      registrations: 'sessions/registrations',
      sessions: 'sessions/sessions',
      unlocks: 'sessions/unlocks',
    }
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  scope :api do
    scope :v7 do
      resources :users
    end
  end

end

app/models/map.rb
class Map < ApplicationRecord
  self.table_name = "aim_maps"
  include SortableScopes
  include FilterScopes
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  load_and_authorize_resource
  include Pagy::Backend

  before_action :set_map, only: %i[ show edit update destroy ]
  before_action :set_maps, only: :index
  before_action :disabled_pagination
  after_action { pagy_headers_merge(@pagy) if @pagy }

  # GET /maps
  def index
    @pagy, @maps = pagy(@maps)

    respond_to do |format|
      format.html
      format.json
      format.turbo_stream
    end
  end

  # GET /maps/search.json
  def search
    @maps = params[:items].present? ? Map.new.filter_by_id(params[:items]) : Map.accessible_by(current_ability)

    respond_to do |format|
      format.json
      format.turbo_stream
    end
  end

  # GET /maps/1
  def show
  end

  # GET /maps/new
  def new
    @map = Map.new
  end

  # GET /maps/1/edit
  def edit
  end

  # POST /maps
  def create
    @map = Map.new(map_params)

    if @map.save
      redirect_to @map, created: I18n.t('map.message.created')
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /maps/1
  def update
    if @map.update(map_params)
      redirect_to @map, updated: I18n.t('map.message.updated'), status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /maps/1
  def destroy
    @map.destroy!
    redirect_to maps_url, delete: I18n.t('map.message.deleted'), status: :see_other
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_map
    @map = Map.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def map_params
    params.require(:map).permit(:name, :top_left_x, :top_left_y, :max_zoom, :bottom_right_x, :max_resolution, :bottom_right_y, :stores_show_from_zoom, :features_radius, :range, :street, :street_number, :parent_id, :lft, :rgt, :depth, :kind, :alias, :last_update, :last_change, :zoom_matrix, :adjustment_data, :map_radius, :map_latitude, :map_longitude, :time_between_notifications, :max_notifications_per_period, :notifications_time_period, :scaled_stores, :properties, :until_zoom, :real_min_zoom, :initial_zoom, :authorization_user_manual_file_name, :authorization_user_manual_content_type, :authorization_user_manual_file_size, :authorization_user_manual_updated_at, :loader_version, :tiles_version, :incident_positioning_system, :country_code, :region_code, :map_classification_id, :map_district_id, :map_orientation, :fusion_table_on_start, :time_zone, :sales_room_m2, :property_type, :cost_center, :show_custom_fields)
  end

  def set_maps
    @maps = Map.accessible_by(current_ability)
    @maps = @maps.send(sort_scope(sort_params[:sort_column].to_s), sort_params[:sort_direction]) if sort_params.present?
    filter_params.each { |attribute, value| @maps = @maps.send(filter_scope(attribute), value) } if filter_params.present?
  end

  def sort_params
    params.permit(:sort_column, :sort_direction)
  end

  def filter_params
    params.permit(:id, :name, :top_left_x, :top_left_y, :max_zoom, :bottom_right_x, :max_resolution, :bottom_right_y, :stores_show_from_zoom, :features_radius, :range, :street, :street_number, :parent_id, :lft, :rgt, :depth, :kind, :alias, :last_update, :last_change, :zoom_matrix, :adjustment_data, :map_radius, :map_latitude, :map_longitude, :time_between_notifications, :max_notifications_per_period, :notifications_time_period, :scaled_stores, :properties, :until_zoom, :real_min_zoom, :initial_zoom, :authorization_user_manual_file_name, :authorization_user_manual_content_type, :authorization_user_manual_file_size, :authorization_user_manual_updated_at, :loader_version, :tiles_version, :incident_positioning_system, :country_code, :region_code, :map_classification_id, :map_district_id, :map_orientation, :fusion_table_on_start, :time_zone, :sales_room_m2, :property_type, :cost_center, :show_custom_fields).reject{|key,value| value.blank? }
  end

  def disabled_pagination
    return render json: Map.all if params[:items] == 'all'
  end
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/views/maps/_buttons.html.erb
<div class="py-2">

  <% unless ['index'].include? action_name %>
    <%= link_to maps_path, class: "text-center inline-flex items-center rounded-lg py-3 px-5 bg-blue-500 hover:bg-blue-600 text-white block font-medium" do %>
      <svg class="w-5 h-4" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 18 10">
        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 5H1m0 0 4 4M1 5l4-4"/>
      </svg>
      <%= I18n.t('maps.actions.index') %>
    <% end %>
  <% end %>

  <% unless ['new'].include? action_name %>
    <%= link_to new_map_path, class: "text-center inline-flex items-center rounded-lg py-3 px-5 bg-blue-500 hover:bg-blue-600 text-white block font-medium" do %>
      <svg class="w-4 h-4 mr-2" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 18 18">
        <path d="M6.143 0H1.857A1.857 1.857 0 0 0 0 1.857v4.286C0 7.169.831 8 1.857 8h4.286A1.857 1.857 0 0 0 8 6.143V1.857A1.857 1.857 0 0 0 6.143 0Zm10 0h-4.286A1.857 1.857 0 0 0 10 1.857v4.286C10 7.169 10.831 8 11.857 8h4.286A1.857 1.857 0 0 0 18 6.143V1.857A1.857 1.857 0 0 0 16.143 0Zm-10 10H1.857A1.857 1.857 0 0 0 0 11.857v4.286C0 17.169.831 18 1.857 18h4.286A1.857 1.857 0 0 0 8 16.143v-4.286A1.857 1.857 0 0 0 6.143 10ZM17 13h-2v-2a1 1 0 0 0-2 0v2h-2a1 1 0 0 0 0 2h2v2a1 1 0 0 0 2 0v-2h2a1 1 0 0 0 0-2Z"/>
      </svg>
      <%= I18n.t('maps.actions.new') %>
    <% end %>
  <% end %>

  <% unless ['index', 'edit', 'new'].include? action_name %>
    <%= link_to edit_map_path(@map), class: "text-center inline-flex items-center rounded-lg py-3 px-5 bg-blue-500 hover:bg-blue-600 text-white block font-medium" do %>
      <svg class="w-4 h-4" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 18">
        <path d="M12.687 14.408a3.01 3.01 0 0 1-1.533.821l-3.566.713a3 3 0 0 1-3.53-3.53l.713-3.566a3.01 3.01 0 0 1 .821-1.533L10.905 2H2.167A2.169 2.169 0 0 0 0 4.167v11.666A2.169 2.169 0 0 0 2.167 18h11.666A2.169 2.169 0 0 0 16 15.833V11.1l-3.313 3.308Zm5.53-9.065.546-.546a2.518 2.518 0 0 0 0-3.56 2.576 2.576 0 0 0-3.559 0l-.547.547 3.56 3.56Z"/>
        <path d="M13.243 3.2 7.359 9.081a.5.5 0 0 0-.136.256L6.51 12.9a.5.5 0 0 0 .59.59l3.566-.713a.5.5 0 0 0 .255-.136L16.8 6.757 13.243 3.2Z"/>
      </svg>
      <%= I18n.t('maps.actions.edit') %>
    <% end %>
  <% end %>

  <% if ['index'].include? action_name %>
    <button class="text-center inline-flex items-center rounded-lg py-3 px-5 bg-blue-500 hover:bg-blue-600 text-white block font-medium" type="button" data-drawer-target="drawer-contact" data-drawer-show="drawer-contact" aria-controls="drawer-contact">
      <svg class="w-4 h-4 mr-2" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 18">
        <path d="M18.85 1.1A1.99 1.99 0 0 0 17.063 0H2.937a2 2 0 0 0-1.566 3.242L6.99 9.868 7 14a1 1 0 0 0 .4.8l4 3A1 1 0 0 0 13 17l.01-7.134 5.66-6.676a1.99 1.99 0 0 0 .18-2.09Z"/>
      </svg>
      <%= I18n.t('maps.actions.filter') %>
    </button>
  <% end %>

</div>

app/views/maps/_filter.html.erb
<%= form_with(model: map, class: "contents") do |form| %>
  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/maps/_form.html.erb
<%= form_with(model: map, class: "contents") do |form| %>
  <% if map.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(map.errors.count, "error") %> prohibited this map from being saved:</h2>

      <ul>
        <% map.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :id %>
    <%= form.text_field :id, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :top_left_x %>
    <%= form.text_field :top_left_x, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :top_left_y %>
    <%= form.text_field :top_left_y, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :max_zoom %>
    <%= form.number_field :max_zoom, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :bottom_right_x %>
    <%= form.text_field :bottom_right_x, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :max_resolution %>
    <%= form.text_field :max_resolution, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :bottom_right_y %>
    <%= form.text_field :bottom_right_y, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :stores_show_from_zoom %>
    <%= form.number_field :stores_show_from_zoom, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :features_radius %>
    <%= form.number_field :features_radius, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :range %>
    <%= form.number_field :range, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :street %>
    <%= form.text_field :street, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :street_number %>
    <%= form.number_field :street_number, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :parent_id %>
    <%= form.number_field :parent_id, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :lft %>
    <%= form.number_field :lft, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :rgt %>
    <%= form.number_field :rgt, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :depth %>
    <%= form.number_field :depth, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :kind %>
    <%= form.text_field :kind, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :alias %>
    <%= form.text_field :alias, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :last_update %>
    <%= form.datetime_field :last_update, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :last_change %>
    <%= form.datetime_field :last_change, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :zoom_matrix %>
    <%= form.text_field :zoom_matrix, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :adjustment_data %>
    <%= form.text_field :adjustment_data, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :map_radius %>
    <%= form.text_field :map_radius, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :map_latitude %>
    <%= form.text_field :map_latitude, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :map_longitude %>
    <%= form.text_field :map_longitude, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :time_between_notifications %>
    <%= form.text_field :time_between_notifications, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :max_notifications_per_period %>
    <%= form.number_field :max_notifications_per_period, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :notifications_time_period %>
    <%= form.text_field :notifications_time_period, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :scaled_stores %>
    <%= form.check_box :scaled_stores, class: "block mt-2 h-5 w-5" %>
  </div>

  <div class="my-5">
    <%= form.label :properties %>
    <%= form.text_field :properties, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :until_zoom %>
    <%= form.number_field :until_zoom, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :real_min_zoom %>
    <%= form.number_field :real_min_zoom, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :initial_zoom %>
    <%= form.number_field :initial_zoom, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :authorization_user_manual_file_name %>
    <%= form.text_field :authorization_user_manual_file_name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :authorization_user_manual_content_type %>
    <%= form.text_field :authorization_user_manual_content_type, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :authorization_user_manual_file_size %>
    <%= form.number_field :authorization_user_manual_file_size, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :authorization_user_manual_updated_at %>
    <%= form.datetime_field :authorization_user_manual_updated_at, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :loader_version %>
    <%= form.number_field :loader_version, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :tiles_version %>
    <%= form.number_field :tiles_version, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :incident_positioning_system %>
    <%= form.text_field :incident_positioning_system, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :country_code %>
    <%= form.text_field :country_code, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :region_code %>
    <%= form.text_field :region_code, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :map_classification_id %>
    <%= form.number_field :map_classification_id, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :map_district_id %>
    <%= form.number_field :map_district_id, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :map_orientation %>
    <%= form.text_field :map_orientation, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :fusion_table_on_start %>
    <%= form.check_box :fusion_table_on_start, class: "block mt-2 h-5 w-5" %>
  </div>

  <div class="my-5">
    <%= form.label :time_zone %>
    <%= form.text_field :time_zone, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :sales_room_m2 %>
    <%= form.text_field :sales_room_m2, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :property_type %>
    <%= form.number_field :property_type, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :cost_center %>
    <%= form.text_field :cost_center, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :show_custom_fields %>
    <%= form.check_box :show_custom_fields, class: "block mt-2 h-5 w-5" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/maps/_map.html.erb
<div id="<%= dom_id map %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Id:</strong>
    <%= map.id %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= map.name %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this map", map, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Edit this map", edit_map_path(map), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/maps/_map_row.html.erb
<tr class="bg-white border-b hover:bg-gray-50">
  <td class="px-6 py-2 font-medium text-gray-900 whitespace-nowrap"><%= map.id %></td>
  <td class="px-6 py-2 font-medium text-gray-900 whitespace-nowrap"><%= map.name %></td>
  <td class="px-6 py-1 text-right flex gap-1">
    <%= link_to map, class: "button-show", 'data-tooltip-target': "tooltip-show_#{map.id}" do %>
      <svg class="w-4 h-4" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
        <path d="m19.707 18.293-4-4a1 1 0 0 0-1.414 1.414l4 4a1 1 0 0 0 1.414-1.414ZM8 .5A7.5 7.5 0 1 0 15.5 8 7.508 7.508 0 0 0 8 .5ZM11 9H9v2a1 1 0 1 1-2 0V9H5a1 1 0 0 1 0-2h2V5a1 1 0 0 1 2 0v2h2a1 1 0 1 1 0 2Z"/>
      </svg>
    <% end %>
    <div id="tooltip-show_<%= map.id %>" role="tooltip" class="absolute z-10 invisible inline-block px-3 py-2 text-sm font-medium text-white transition-opacity duration-300 bg-gray-900 rounded-lg shadow-sm opacity-0 tooltip"><%= I18n.t('maps.actions.show', id: map.id) %><div class="tooltip-arrow" data-popper-arrow></div></div>
    <%= link_to edit_map_path(map), class: "button-edit", 'data-tooltip-target': "tooltip-edit_#{map.id}" do %>
      <svg class="w-4 h-4" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 18">
        <path d="M12.687 14.408a3.01 3.01 0 0 1-1.533.821l-3.566.713a3 3 0 0 1-3.53-3.53l.713-3.566a3.01 3.01 0 0 1 .821-1.533L10.905 2H2.167A2.169 2.169 0 0 0 0 4.167v11.666A2.169 2.169 0 0 0 2.167 18h11.666A2.169 2.169 0 0 0 16 15.833V11.1l-3.313 3.308Zm5.53-9.065.546-.546a2.518 2.518 0 0 0 0-3.56 2.576 2.576 0 0 0-3.559 0l-.547.547 3.56 3.56Z"/>
        <path d="M13.243 3.2 7.359 9.081a.5.5 0 0 0-.136.256L6.51 12.9a.5.5 0 0 0 .59.59l3.566-.713a.5.5 0 0 0 .255-.136L16.8 6.757 13.243 3.2Z"/>
      </svg>
    <% end %>
    <div id="tooltip-edit_<%= map.id %>" role="tooltip" class="absolute z-10 invisible inline-block px-3 py-2 text-sm font-medium text-white transition-opacity duration-300 bg-gray-900 rounded-lg shadow-sm opacity-0 tooltip"><%= I18n.t('maps.actions.edit', id: map.id) %><div class="tooltip-arrow" data-popper-arrow></div></div>
    <%= link_to map, class: "button-delete", method: :delete, 'data-tooltip-target': "tooltip-delete_#{map.id}" do %>
      <svg class="w-4 h-4" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 18 20">
        <path d="M17 4h-4V2a2 2 0 0 0-2-2H7a2 2 0 0 0-2 2v2H1a1 1 0 0 0 0 2h1v12a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V6h1a1 1 0 1 0 0-2ZM7 2h4v2H7V2Zm1 14a1 1 0 1 1-2 0V8a1 1 0 0 1 2 0v8Zm4 0a1 1 0 0 1-2 0V8a1 1 0 0 1 2 0v8Z"/>
      </svg>
    <% end %>
    <div id="tooltip-delete_<%= map.id %>" role="tooltip" class="absolute z-10 invisible inline-block px-3 py-2 text-sm font-medium text-white transition-opacity duration-300 bg-gray-900 rounded-lg shadow-sm opacity-0 tooltip"><%= I18n.t('maps.actions.delete', id: map.id) %><div class="tooltip-arrow" data-popper-arrow></div></div>
  </td>
</tr>

app/views/maps/edit.html.erb
<div class="w-full">
  <div class="py-2 flex justify-between items-center">
    <h1 class="font-bold text-4xl"><%= I18n.t 'maps.properties.title' %></h1>
    <h3 class="font-bold text-xl"><%= I18n.t 'maps.actions.edit', id: @map.id %></h3>
  </div>

  <%= render "buttons" %>

  <%= render "form", map: @map %>

</div>

app/views/maps/new.html.erb
<div class="w-full">
  <div class="py-2 flex justify-between items-center">
    <h1 class="font-bold text-4xl"><%= I18n.t 'maps.properties.title' %></h1>
    <h3 class="font-bold text-xl"><%= I18n.t 'maps.actions.new', id: @map.id %></h3>
  </div>

  <%= render "buttons" %>

  <%= render "form", map: @map %>

</div>