config/routes.rb
Rails.application.routes.draw do
  resources :test_posts
  resources :test_tags
  resources :test_articles

  # Test Resources
  resources :test_tags do
    collection do
      get :search
    end
  end
  resources :test_articles do
    collection do
      get :search
    end
  end
  resources :test_posts do
    collection do
      get :search
    end
  end

  # Core Resources
  resources :roles do
    collection do
      get :search
    end
  end
  resources :profiles do
    collection do
      get :search
    end
  end
  resources :groups do
    collection do
      get :search
    end
  end
  resources :users do
    collection do
      get :search
    end
  end
  resources :maps do
    collection do
      get :search
    end
  end

  # Defines the root path route ("/")
  root "homepage#index"

  get 'test/create' => 'homepage#create'
  get 'test/update' => 'homepage#update'
  get 'test/delete' => 'homepage#destroy'

  scope :sessions do
    devise_for :users, controllers: {
      confirmations: 'sessions/confirmations',
      onmiauth_callbacks: 'sessions/onmiauth_callbacks',
      passwords: 'sessions/passwords',
      registrations: 'sessions/registrations',
      sessions: 'sessions/sessions',
      unlocks: 'sessions/unlocks',
    }
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  scope :api do
    scope :v7 do
      resources :users
    end
  end

end

app/models/test_article.rb
class TestArticle < ApplicationRecord
  self.table_name = "test_articles"
  include SortableScopes
  include FilterScopes
  has_secure_password
  acts_as_paranoid
end

app/controllers/test_articles_controller.rb
class TestArticlesController < ApplicationController
  load_and_authorize_resource
  include Pagy::Backend

  before_action :set_test_article, only: %i[ show edit update destroy ]
  before_action :set_test_articles, only: :index
  before_action :disabled_pagination
  after_action { pagy_headers_merge(@pagy) if @pagy }

  # GET /test_articles
  def index
    @pagy, @test_articles = pagy(@test_articles)

    respond_to do |format|
      format.html
      format.json
      format.turbo_stream
    end
  end

  # GET /test_articles/search.json
  def search
    @test_articles = params[:items].present? ? TestArticle.new.filter_by_id(params[:items]) : TestArticle.accessible_by(current_ability)

    respond_to do |format|
      format.json
      format.turbo_stream
    end
  end

  # GET /test_articles/1
  def show
    @test_article
  end

  # GET /test_articles/new
  def new
    @test_article = TestArticle.new
  end

  # GET /test_articles/1/edit
  def edit
  end

  # POST /test_articles
  def create
    @test_article = TestArticle.new(test_article_params)

    if @test_article.save
      redirect_to @test_article, created: I18n.t('test_article.message.created')
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /test_articles/1
  def update
    if @test_article.update(test_article_params)
      redirect_to @test_article, updated: I18n.t('test_article.message.updated'), status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /test_articles/1
  def destroy
    #@test_article.destroy!
    flash.now[:deleted] = I18n.t('test_article.message.deleted')
    respond_to do |format|
      format.html { redirect_to test_articles_path, deleted: I18n.t('test_article.message.deleted'), status: :see_other }
      format.json { head :no_content }
      format.turbo_stream { render turbo_stream: [ turbo_stream.remove("test_article_#{@test_article.id}"), turbo_stream.update("turbo-notification", partial: 'layouts/shared/notification_row') ] }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_test_article
    @test_article = TestArticle.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def test_article_params
    params.require(:test_article).permit(:name, :content, :option, :password, :password_confirmation)
  end

  def set_test_articles
    @test_articles = TestArticle.accessible_by(current_ability) || TestArticle.none
    @test_articles = @test_articles.send(sort_scope(sort_params[:sort_column].to_s), sort_params[:sort_direction]) if sort_params.present?
    filter_params.each { |attribute, value| @test_articles = @test_articles.send(filter_scope(attribute), value) } if filter_params.present?
  end

  def sort_params
    params.permit(:sort_column, :sort_direction)
  end

  def filter_params
    params.permit(:id, :name, :content, :option, :password, :password_confirmation).reject{|key,value| value.blank? }
  end

  def disabled_pagination
    return render json: TestArticle.all if params[:items] == 'all'
  end
end

app/helpers/test_articles_helper.rb
module TestArticlesHelper
end

app/views/test_articles/_buttons.html.erb
<div class="button-container">

  <% if %w[index].include? action_name %>
    <%= button_tag raw(icon('filter') + icon_text(I18n.t('test_articles.actions.filter'))), name: 'filter', type: 'button', class: "button-filter", data: { 'drawer-target': "drawer-filter", 'drawer-show': "drawer-filter", 'aria-controls': "drawer-filter" } %>
  <% end %>

  <% unless %w[index].include? action_name %>
    <%= link_to raw(icon('back') + icon_text(I18n.t('test_articles.actions.index'))), test_articles_path, class: "button-general" %>
  <% end %>

  <% unless %w[new create edit update].include? action_name %>
    <%= link_to raw(icon('new') + icon_text(I18n.t('test_articles.actions.new'))), new_test_article_path, class: "button-new" %>
  <% end %>

  <% unless %w[new create edit update index].include? action_name %>
    <%= link_to raw(icon('edit') + icon_text(I18n.t('test_articles.actions.edit'))), edit_test_article_path(@test_article), class: "button-edit" %>
  <% end %>

  <% unless %w[new create edit update index].include? action_name %>
    <%= button_tag raw(icon('delete') + icon_text(I18n.t('test_articles.actions.delete'))), type: "button", class: "button-delete", data: {'modal-target': "deleteModal", 'modal-toggle': "deleteModal"} %>

    <div id="deleteModal" tabindex="-1" aria-hidden="true" class="hidden overflow-y-auto overflow-x-hidden fixed top-0 right-0 left-0 z-50 justify-center items-center w-full md:inset-0 h-modal md:h-full">
      <div class="relative p-4 w-full max-w-md h-full md:h-auto">
        <div class="relative p-4 text-center bg-white rounded-lg shadow sm:p-5">
          <%= button_tag raw(icon('close', 'w-3 h-3')), name: 'filter', type: 'button', class: "button-close", data: { 'modal-toggle': "deleteModal" } %>
          <%= icon('delete', 'text-gray-400 dark:text-gray-500 w-11 h-11 mb-3.5 mx-auto') %>
          <p class="mb-4 text-gray-500 dark:text-gray-300">Are you sure you want to delete this item?</p>
          <div class="flex justify-center items-center space-x-4">
            <%= button_tag 'Cancelar', type: 'button', class: 'py-2 px-3 text-sm font-medium text-gray-500 bg-white rounded-lg border border-gray-200 hover:bg-gray-100 focus:ring-4 focus:outline-none focus:ring-primary-300 hover:text-gray-900 focus:z-10 dark:bg-gray-700 dark:text-gray-300 dark:border-gray-500 dark:hover:text-white dark:hover:bg-gray-600 dark:focus:ring-gray-600', data: {'modal-toggle': "deleteModal"} %>
            <%= link_to raw(icon_text(I18n.t('test_articles.actions.delete'))), test_article_path(@test_article), class: "button-danger", data: { turbo_method: :delete } %>
          </div>
        </div>
      </div>
    </div>
  <% end %>

</div>

app/views/test_articles/_filter.html.erb
<div id="drawer-filter" class="drawer-container -translate-x-full" tabindex="-1" aria-labelledby="drawer-filter-label">
  <h5 id="drawer-label" class="drawer-title">
    <%= icon('filter') + icon_text(I18n.t('test_articles.actions.filter')) %>
  </h5>

  <%= button_tag raw(icon('close', 'w-3 h-3')), name: 'filter', type: 'button', class: "button-close", data: { 'drawer-hide': "drawer-filter", 'aria-controls': "drawer-filter" } %>

  <%= form_tag test_articles_path, method: :get do %>

    <div class="form-field">
      <%= label_tag :id, I18n.t('activerecord.attributes.test_article.id'), class: "form-label" %>
      <%= text_field_tag :id, params[:id], class: "form-control" %>
    </div>

    <div class="form-field">
      <%= label_tag :name, I18n.t('activerecord.attributes.test_article.name'), class: "form-label" %>
      <%= text_field_tag :name, params[:name], class: "form-control" %>
    </div>

    <div class="form-button">
      <%= button_tag raw(icon('filter') + icon_text(I18n.t('test_articles.actions.filter'))), type: 'submit', class: "button-filter button-block" %>
    </div>

  <% end %>

  <div class="form-button">
    <%= link_to raw(icon('trash') + icon_text(I18n.t('test_articles.actions.clean'))), test_articles_path, class: "button-delete button-block" %>
  </div>

</div>

app/views/test_articles/_form.html.erb
<%= form_with(model: test_article, class: "form-container") do |form| %>

  <div class="form-field">
    <% invalid = test_article.errors.include?(:id) %>
    <%= form.label :id, I18n.t('activerecord.attributes.test_article.id'), class: "form-label" %>
    <%= form.text_field :id, class: "form-control #{'form-control-invalid' if invalid}" %>
    <%= raw(error_message(invalid, test_article.errors.full_messages_for(:id))) %>
  </div>

  <div class="form-field">
    <% invalid = test_article.errors.include?(:name) %>
    <%= form.label :name, I18n.t('activerecord.attributes.test_article.name'), class: "form-label" %>
    <%= form.text_field :name, class: "form-control #{'form-control-invalid' if invalid}" %>
    <%= raw(error_message(invalid, test_article.errors.full_messages_for(:name))) %>
  </div>

  <div class="form-field">
    <% invalid = test_article.errors.include?(:content) %>
    <%= form.label :content, I18n.t('activerecord.attributes.test_article.content'), class: "form-label" %>
    <%= form.text_area :content, rows: 4, class: "form-control #{'form-control-invalid' if invalid}" %>
    <%= raw(error_message(invalid, test_article.errors.full_messages_for(:content))) %>
  </div>

  <div class="form-field">
    <% invalid = test_article.errors.include?(:option) %>
    <div class="form-checkbox-container">
      <%= form.check_box :option, class: "form-checkbox-control" %>
      <%= form.label :option, I18n.t('activerecord.attributes.test_article.option'), class: "form-checkbox-label" %>
    </div>
    <%= raw(error_message(invalid, test_article.errors.full_messages_for(:option))) %>
  </div>

  <div class="form-field">
    <% invalid = test_article.errors.include?(:password) %>
    <%= form.label :password, I18n.t('activerecord.attributes.test_article.password'), class: "form-label" %>
    <%= form.password_field :password, class: "form-control #{'form-control-invalid' if invalid}" %>
    <%= raw(error_message(invalid, test_article.errors.full_messages_for(:password))) %>
  </div>

  <div class="form-field">
    <% invalid = test_article.errors.include?(:password_confirmation) %>
    <%= form.label :password_confirmation, I18n.t('activerecord.attributes.test_article.password_confirmation'), class: "form-label" %>
    <%= form.password_field :password_confirmation, class: "form-control #{'form-control-invalid' if invalid}" %>
    <%= raw(error_message(invalid, test_article.errors.full_messages_for(:password_confirmation))) %>
  </div>

  <div class="form-actions">
    <%= form.submit I18n.t('test_articles.actions.create'), class: "form-submit" %>
  </div>
<% end %>

app/views/test_articles/_table.html.erb
<div class="table-paginator" data-controller="pagy-initializer"><%== pagy_nav(@pagy) %></div>

<div class="table-container">
  <table class="table-index">
    <thead class="table-header">
    <tr>
      <th scope="col" class="table-attribute"><%= sort_link('test_articles_path', I18n.t('activerecord.attributes.test_article.id'), 'id') %></th>
      <th scope="col" class="table-attribute"><%= sort_link('test_articles_path', I18n.t('activerecord.attributes.test_article.name'), 'name') %></th>
      <th scope="col" class="table-attribute-actions"><%= I18n.t('operator.actions') %></th>
    </tr>
    </thead>
    <tbody>
    <% @test_articles.each.with_index do |test_article| %>
      <%= render partial: "test_article_row", locals: { test_article: test_article } %>
    <% end %>
    </tbody>
  </table>
</div>

app/views/test_articles/_test_article.html.erb
<div id="<%= dom_id test_article %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Id:</strong>
    <%= test_article.id %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= test_article.name %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this test article", test_article, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Edit this test article", edit_test_article_path(test_article), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/test_articles/_test_article_row.html.erb
<tr class="table-row" id="test_article_<%= test_article.id %>">
  <td class="table-cell"><%= test_article.id %></td>
  <td class="table-cell"><%= test_article.name %></td>
  <td class="table-actions">
    <%= link_to raw(icon('show', 'w-4 h-4')), test_article, class: "button-row button-show", data: {'tooltip-target': "tooltip-show_#{test_article.id}", 'tooltip-placement': "left"} %>
    <div id="tooltip-show_<%= test_article.id %>" role="tooltip" class="button-tooltip invisible transition-opacity duration-300 opacity-0 tooltip"><%= I18n.t('test_articles.actions.show', id: test_article.id) %><div class="tooltip-arrow" data-popper-arrow></div></div>
    <%= link_to raw(icon('edit', 'w-4 h-4')), edit_test_article_path(test_article), class: "button-row button-edit", data: {'tooltip-target': "tooltip-edit_#{test_article.id}", 'tooltip-placement': "left"} %>
    <div id="tooltip-edit_<%= test_article.id %>" role="tooltip" class="button-tooltip invisible transition-opacity duration-300 opacity-0 tooltip"><%= I18n.t('test_articles.actions.edit', id: test_article.id) %><div class="tooltip-arrow" data-popper-arrow></div></div>
    <%= link_to raw(icon('delete', 'w-4 h-4')), test_article, class: "button-row button-delete", method: :delete, data: {'tooltip-target': "tooltip-delete_#{test_article.id}", 'tooltip-placement': "left"} %>
    <div id="tooltip-delete_<%= test_article.id %>" role="tooltip" class="button-tooltip invisible transition-opacity duration-300 opacity-0 tooltip"><%= I18n.t('test_articles.actions.delete', id: test_article.id) %><div class="tooltip-arrow" data-popper-arrow></div></div>
    <%= link_to raw(icon('delete', 'w-4 h-4')), test_article, method: :delete, class: "button-row button-delete", data: { turbo_method: :delete, turbo_confirm: 'Seguro?' } %>
  </td>
</tr>

app/views/test_articles/edit.html.erb
<div class="container-fluid">
  <div class="container-title">
    <h1 class="title-text"><%= I18n.t 'test_articles.properties.title' %></h1>
    <h3 class="subtitle-text"><%= I18n.t 'test_articles.actions.edit', id: @test_article.id %></h3>
  </div>

  <%= render "buttons" %>

  <%= render "form", test_article: @test_article %>

</div>

app/views/test_articles/index.html.erb
<div class="container-fluid">
  <div class="container-title">
    <h1 class="title-text"><%= I18n.t 'test_articles.properties.title' %></h1>
  </div>

  <%= render "buttons" %>

  <%= render "table" %>

  <%= render "filter" %>

  <%#= render 'layouts/shared/confirm' %>

</div>

app/views/test_articles/new.html.erb
<div class="container-fluid">
  <div class="container-title">
    <h1 class="title-text"><%= I18n.t 'test_articles.properties.title' %></h1>
    <h3 class="subtitle-text"><%= I18n.t 'test_articles.actions.new', id: @test_article.id %></h3>
  </div>

  <%= render "buttons" %>

  <%= render "form", test_article: @test_article %>

</div>

app/views/test_articles/show.html.erb
<div class="container-fluid">
  <div class="container-title">
    <h1 class="title-text"><%= I18n.t 'test_articles.properties.title' %></h1>
    <h3 class="subtitle-text"><%= I18n.t 'test_articles.actions.show', id: @test_article.id %></h3>
  </div>

  <%= render "buttons" %>

  <%= render @test_article %>

</div>